# mystic-crypt .travis.yml

language: java

jdk:
    - oraclejdk8

notifications:
    email:
        recipients:
            - asterios.raptis@web.de
        on_failure: always
        
after_success:
  - mvn clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:report
