dependencies {

    implementation libs.commons.codec
    implementation libs.commons.io
    implementation libs.commons.lang3
    api libs.guava
    api libs.crypt.api
    api libs.crypt.data
    implementation libs.throwable
    implementation libs.randomizer
    implementation libs.file.worker
    implementation libs.silly.collection
    implementation libs.jobj.core
    api libs.silly.bean
    implementation libs.jobj.cloner
    api libs.bcprov.jdk18on
    implementation libs.bcprov.ext.jdk18on
    implementation libs.bcpkix.jdk18on
    implementation libs.xml.base
    // command-line interface (io.github.astrapi69.mystic.crypt.cli)
    implementation libs.picocli

    testImplementation libs.silly.strings
    testImplementation libs.json.extensions
    testImplementation libs.checksum.up
    testImplementation libs.test.object
    testImplementation libs.silly.io
    testImplementation libs.random.beans
    // Note: use of bundles...
    testImplementation libs.bundles.unit.testing
    testRuntimeOnly libs.junit.platform.launcher

}
