name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Welcome to mystic-crypt and thanks for your first issue and helping us out to make our library better'' first issue'
        pr-message: 'Welcome to mystic-crypt and thanks for your first pull request and helping us out to make our library better'' first pr'
